name: Nightly Deploy

on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: fjogeleit/http-request-action@master
      with:
        url:  ${{ secrets.DEPLOY_HOOK_URL }}
        method: 'GET'
        timeout: 30000
        preventFailureOnNoResponse: true
